-- Report R-B schema for shop_recommendations (CENTRAL contract).
--
-- A resident report preserves the reporter's raw relation text and may arrive
-- without a canonical category or a resolvable relation. The legacy intake
-- fields stay readable for history but carry no approval authority:
--   - category_name is nullable legacy text (raw, unresolved values allowed)
--   - relation_type is nullable legacy text (set only when pre-resolved)
-- Approval authority is ONLY resolved_category_id + resolved_relation_type.
-- Approval fails closed when either is null or the category is inactive.
-- Raw relation is ALWAYS preserved; nearby -> local auto-resolve is
-- FORBIDDEN (nearby stays raw with resolved_relation_type NULL).
--
-- Purely additive except the two legacy NOT NULL relaxations:
--   - no DROP TABLE / TRUNCATE / DELETE
--   - existing rows keep their legacy values; reported_relation_raw is
--     backfilled from the legacy relation_type so history stays readable.

-- 1) Legacy intake fields become nullable.
alter table shop_recommendations alter column category_name drop not null;
alter table shop_recommendations alter column relation_type drop not null;

-- 2) Rebuild the old non-nullable checks with null-tolerant equivalents.
--    Constraint names are auto-generated by 029, so drop by definition.
--    PostgreSQL normalizes `in (...)` to `= ANY (ARRAY[...])`; the old defs
--    are exactly the ones without an IS NULL branch, so the new null-tolerant
--    checks are never matched and reruns stay no-ops.
do $$
declare c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'shop_recommendations'::regclass
      and contype = 'c'
      and (
        (pg_get_constraintdef(oid) like '%(relation_type = ANY%'
         and pg_get_constraintdef(oid) not like '%IS NULL%')
        or (pg_get_constraintdef(oid) like '%char_length(category_name)%'
            and pg_get_constraintdef(oid) not like '%IS NULL%')
      )
  loop
    execute format('alter table shop_recommendations drop constraint %I', c.conname);
  end loop;
end
$$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_relation_type_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_relation_type_check
        check (relation_type is null or relation_type in ('resident_family','neighbor','local'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_category_name_length_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_category_name_length_check
        check (category_name is null or char_length(category_name) between 1 and 120);
  end if;
end
$$;

-- 3) Report R-B columns.
alter table shop_recommendations
  add column if not exists reported_relation_raw text;
alter table shop_recommendations
  add column if not exists resolved_relation_type text;
alter table shop_recommendations
  add column if not exists relation_detail text;
alter table shop_recommendations
  add column if not exists resolved_category_id uuid references business_categories(id) on delete set null;
alter table shop_recommendations
  add column if not exists report_price text;
alter table shop_recommendations
  add column if not exists report_hours text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_reported_relation_raw_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_reported_relation_raw_check
        check (reported_relation_raw is null or char_length(reported_relation_raw) <= 120);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_resolved_relation_type_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_resolved_relation_type_check
        check (resolved_relation_type is null or resolved_relation_type in ('resident_family','neighbor','local'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_relation_detail_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_relation_detail_check
        check (relation_detail is null or char_length(relation_detail) <= 1000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_report_price_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_report_price_check
        check (report_price is null or char_length(report_price) <= 120);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'shop_recommendations_report_hours_check') then
    alter table shop_recommendations
      add constraint shop_recommendations_report_hours_check
        check (report_hours is null or char_length(report_hours) <= 120);
  end if;
end
$$;

-- 4) Preserve the raw relation for history written before this migration.
update shop_recommendations
set reported_relation_raw = relation_type
where reported_relation_raw is null
  and relation_type is not null;

create index if not exists idx_shop_recommendations_resolved_category
  on shop_recommendations (resolved_category_id);

comment on column shop_recommendations.reported_relation_raw is
  'Report R-B raw relation text, always preserved verbatim. nearby stays raw; nearby -> local auto-resolve is forbidden.';
comment on column shop_recommendations.resolved_relation_type is
  'Report R-B resolved relation. Only family -> resident_family and neighbor -> neighbor may be auto-pre-resolved at intake. Joint approval authority with resolved_category_id.';
comment on column shop_recommendations.relation_detail is
  'Report R-B free-text relation detail (e.g. etc lane), preserved verbatim.';
comment on column shop_recommendations.resolved_category_id is
  'Report R-B resolved canonical category. Joint approval authority with resolved_relation_type. Legacy category_name is not an approval authority.';
comment on column shop_recommendations.report_price is
  'Report R-B reported price text, verbatim product copy. Not a settlement calculation.';
comment on column shop_recommendations.report_hours is
  'Report R-B reported hours text, verbatim product copy.';

-- DOWN:
-- drop index if exists idx_shop_recommendations_resolved_category;
-- update shop_recommendations set reported_relation_raw = null;
-- alter table shop_recommendations drop constraint if exists shop_recommendations_report_hours_check;
-- alter table shop_recommendations drop constraint if exists shop_recommendations_report_price_check;
-- alter table shop_recommendations drop constraint if exists shop_recommendations_relation_detail_check;
-- alter table shop_recommendations drop constraint if exists shop_recommendations_resolved_relation_type_check;
-- alter table shop_recommendations drop constraint if exists shop_recommendations_reported_relation_raw_check;
-- alter table shop_recommendations drop column if exists report_hours;
-- alter table shop_recommendations drop column if exists report_price;
-- alter table shop_recommendations drop column if exists resolved_category_id;
-- alter table shop_recommendations drop column if exists relation_detail;
-- alter table shop_recommendations drop column if exists resolved_relation_type;
-- alter table shop_recommendations drop column if exists reported_relation_raw;
