-- Owner application relation resolution for business_applications (CENTRAL contract #341).
--
-- The owner lane collects a canonical raw relation (self | co | family | etc).
-- Only self and family pre-resolve to the projection enum; co and etc are
-- stored UNRESOLVED and approval fails closed until a reviewer resolution
-- path exists. No co -> neighbor and no etc -> * inference is permitted.
--   - relation_raw preserves the owner's canonical choice verbatim.
--   - resolved_relation_type is the new resolution authority (projection enum).
--   - legacy relation_type stays readable for history and mirrors the resolved
--     value on new writes; it carries no independent approval authority.
-- business_complex_relations keeps its existing four-value meaning unchanged.
--
-- Purely additive except the one legacy NOT NULL relaxation:
--   - no DROP TABLE / TRUNCATE / DELETE
--   - existing rows keep their legacy values; resolved_relation_type is
--     backfilled from the legacy relation_type so history stays approvable.

-- 1) The legacy intake field becomes nullable (unresolved co/etc store NULL).
alter table business_applications alter column relation_type drop not null;

-- 2) Rebuild the old non-nullable check with a null-tolerant equivalent.
--    Constraint names are auto-generated by 001, so drop by definition.
--    PostgreSQL normalizes `in (...)` to `= ANY (ARRAY[...])`; the old def is
--    exactly the one without an IS NULL branch, so the new null-tolerant check
--    is never matched and reruns stay no-ops.
do $$
declare c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'business_applications'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%(relation_type = ANY%'
      and pg_get_constraintdef(oid) not like '%IS NULL%'
  loop
    execute format('alter table business_applications drop constraint %I', c.conname);
  end loop;
end
$$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'business_applications_relation_type_check') then
    alter table business_applications
      add constraint business_applications_relation_type_check
        check (relation_type is null or relation_type in ('resident','resident_family','neighbor','local'));
  end if;
end
$$;

-- 3) Owner relation resolution columns.
alter table business_applications
  add column if not exists relation_raw text;
alter table business_applications
  add column if not exists resolved_relation_type text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'business_applications_relation_raw_check') then
    alter table business_applications
      add constraint business_applications_relation_raw_check
        check (relation_raw is null or relation_raw in ('self','co','family','etc'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'business_applications_resolved_relation_type_check') then
    alter table business_applications
      add constraint business_applications_resolved_relation_type_check
        check (resolved_relation_type is null or resolved_relation_type in ('resident','resident_family','neighbor','local'));
  end if;
end
$$;

-- 4) Backfill. Every pre-migration row passed the legacy four-value whitelist,
--    so its legacy relation_type is a valid resolved value; mirror it to keep
--    existing applications approvable under the new gate.
update business_applications
set resolved_relation_type = relation_type
where resolved_relation_type is null
  and relation_type is not null;

-- Preserve the raw canonical choice only through the safe inverse mapping
-- (resident -> self, resident_family -> family). neighbor / local rows have no
-- canonical raw equivalent and stay NULL; no inference is performed.
update business_applications
set relation_raw = case relation_type
                     when 'resident' then 'self'
                     when 'resident_family' then 'family'
                   end
where relation_raw is null
  and relation_type in ('resident','resident_family');

comment on column business_applications.relation_raw is
  'Owner application canonical raw relation (self|co|family|etc), preserved verbatim. co and etc carry no auto-resolved projection.';
comment on column business_applications.resolved_relation_type is
  'Owner application resolution authority (projection enum). Only self -> resident and family -> resident_family pre-resolve at intake; NULL blocks approval fail-closed.';
comment on column business_applications.relation_type is
  'Legacy owner application relation field. Mirrors resolved_relation_type on new writes and keeps history readable; approval requires it to be non-null.';

-- DOWN:
-- update business_applications set relation_raw = null, resolved_relation_type = null;
-- alter table business_applications drop constraint if exists business_applications_resolved_relation_type_check;
-- alter table business_applications drop constraint if exists business_applications_relation_raw_check;
-- alter table business_applications drop column if exists resolved_relation_type;
-- alter table business_applications drop column if exists relation_raw;
-- alter table business_applications drop constraint if exists business_applications_relation_type_check;
-- update business_applications set relation_type = 'resident' where relation_type is null;
-- alter table business_applications alter column relation_type set not null;
-- alter table business_applications add constraint business_applications_relation_type_check check (relation_type in ('resident','resident_family','neighbor','local'));
